
###

GET http://localhost:4000/posts

###

GET http://localhost:3000/posts/673765ba49f7560f5d444c27

###

POST http://localhost:4000/posts
Content-Type: application/json

{
    "owner": "Eden",
    "title": "My First Post",
    "content": "This is my first post"
}

