
###
// Get all posts
GET http://localhost:4000/posts

###
// Get post by sender
GET http://localhost:4000/posts?sender=Eden2

###
// Get post by id
GET http://localhost:4000/posts/67519863c75b61c38670381d

###
// Create a new post
POST http://localhost:4000/posts
Content-Type: application/json

{
    "sender": "Eden",
    "title": "My First Post",
    "content": "This is my first post"
}

###
// Update a post
PUT http://localhost:4000/posts/67519863c75b61c38670381d
Content-Type: application/json

{
    "sender": "Eden",
    "title": "My Second Post",
    "content": "This is my second post"
}

###
// Delete a post
DELETE http://localhost:4000/posts/6751c9fd29b8f72bfff00059

###
//all comments
GET http://localhost:4000/comments


###

POST http://localhost:4000/comments
Content-Type: application/json

{
  "comment": "This is a new comment",
  "author": "Eden",
  "postId": "6754237446da0f9a20100dd9"
}

###
//get comment by pot id
GET http://localhost:4000/comments?postId=67519863c75b61c38670381d


### 
//Update a comment
PUT http://localhost:4000/comments/67519940c75b61c38670383a
Content-Type: application/json

{
  "comment": "Updated comment",
  "author": "Yoav"
}

### 
//Delete a comment
DELETE http://localhost:4000/comments/67519944c75b61c38670383d